services:
  db:
    image: postgres:15
    container_name: magalu_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=magaludb
      - POSTGRES_USER=magaluuser
      - POSTGRES_PASSWORD=magalupass
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: magalu_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: magalu_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db 
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=magaludb
      - DB_USER=magaluuser
      - DB_PASS=magalupass

  worker:
    build: .
    container_name: magalu_worker
    command: python -m celery -A setup worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
      - db 
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=magaludb
      - DB_USER=magaluuser
      - DB_PASS=magalupass
      
volumes:
  postgres_data: